---
sidebar: sidebar 
permalink: reference_requirements_vcp.html 
summary: 开始使用适用于 vCenter Server 的 NetApp Element 插件之前，您需要了解产品安装和使用的前提条件。 
keywords: netapp, hci, kubernetes, on premise, cloud services 
---
= 适用于 vCenter Server 的 Element 插件的要求
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在使用适用于 vCenter Server 的 NetApp Element 插件管理 NetApp HCI 或 SolidFire 全闪存阵列存储之前，您需要确保系统满足插件使用要求。​



== VMware vSphere 前提条件

要使用适用于 vCenter Server 的 NetApp Element 插件，需要使用 VMware vSphere 7.0 或 6.7 ，包括配置了软件 iSCSI 适配器和 iSCSI 网络的 vCenter 和 ESXi 。



=== 此插件支持的 VMware vSphere 版本

此插件支持以下主要版本的 VMware 软件：

* vSphere 7.0 和 7.0 Update 1 ，包括 vCenter Server ， ESXi 以及 VMFS5 和 VMFS6 数据存储库
* vSphere 6.7 和 6.7 Update 1 和 3 ，包括 vCenter Server ， ESXi 以及 VMFS5 和 VMFS6 数据存储库
+

IMPORTANT: 此插件与 HTML5 vSphere Web Client 的 6.7 U2 内部版本 13007421 以及更新 2a （内部版本 13643870 ）之前发布的其他 6.7 U2 内部版本不兼容。它与适用于 Flash/FLEX 的 vSphere Web Client 6.7 U2 版兼容。




IMPORTANT: 此插件与 VMware vCenter Server 6.5 不兼容。



=== 停止 vSphere 6.0 支持


IMPORTANT: VMware vSphere 6.0 已于 2020 年 3 月 12 日停止支持。从 NetApp HCI 1.8 和 Element 12 开始，不再支持 vSphere 6.0 。有关详细信息，请参见此 https://mysupport.netapp.com/info/communications/ECMLP2863840.html["产品公告"]。



== vSphere 兼容性和最佳实践

在使用此插件之前，请考虑以下功能和建议：

* 不支持 vCenter 高可用性（ VCHA ）。
* 由于数据存储库是使用选定 ESXi 主机支持的最高 VMFS 版本创建的，因此所有集群成员都应运行相同版本的 vSphere 和 ESXi ，以避免出现 VMFS 兼容性问题。
* vSphere HTML5 Web Client 和 Flash Web Client 具有单独的数据库，这些数据库不能组合使用。在一个客户端中添加的集群在另一个客户端中不可见。如果要同时使用这两个客户端，请在这两个客户端中添加集群。




== NetApp Element 支持

此插件支持以下主要版本：

* Element 12.x ，包括 SolidFire 企业 SDS
* Element 11.x




== 网络端口要求

您需要允许某些 TCP 端口通过数据中心的边缘防火墙，以便可以远程管理系统，并允许数据中心外部的客户端连接到资源。有关 NetApp HCI 和 SolidFire 系统中使用的端口的完整列表，请参见此部分 link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html["页面。"]。

[discrete]
== 了解更多信息

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]

