---
sidebar: sidebar 
permalink: reference_requirements_vcp.html 
summary: 开始使用适用于VMware vCenter Server的NetApp Element 插件之前、您需要了解产品安装和使用的前提条件。 
keywords: netapp, hci, kubernetes, on premise, cloud services 
---
= 适用于VMware vCenter Server的NetApp Element 插件的要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在使用适用于VMware vCenter Server的NetApp Element 插件管理NetApp HCI 或SolidFire 全闪存阵列存储之前、您必须验证系统是否满足插件使用要求。

[role="tabbed-block"]
====
.适用于vCenter 5.0或更高版本的Element插件
--
验证您的系统是否满足使用Element vCenter插件5.0或更高版本的要求。

要使用Element vCenter插件、需要使用已配置软件iSCSI适配器和iSCSI网络的VMware vSphere 8.0和7.0、包括vCenter和ESXi。

此插件支持以下主要版本的 VMware 软件：

* vSphere 8.0、包括vCenter Server、ESXi、VMFS5和VMFS6数据存储库
* vSphere 7.0和7.0 Update 1、2和3、包括vCenter Server、ESXi、VMFS5和VMFS6数据存储库



IMPORTANT: VMware vSphere 6.5和6.7已于2022年10月15日停止支持。从Element插件5.0开始、不再支持vSphere 6.5和6.7。有关详细信息，请参见此 https://core.vmware.com/blog/reminder-vsphere-6567-end-general-support["文章"^]。

--
.适用于vCenter 4.10或更早版本的Element插件
--
验证您的系统是否满足使用Element vCenter插件4.10或更早版本的要求。

要使用Element vCenter插件、需要使用VMware vSphere 7.0、6.7或6.5、包括配置了软件iSCSI适配器和iSCSI网络的vCenter和ESXi。

此插件支持以下主要版本的 VMware 软件：

* vSphere 7.0和7.0 Update 1和2、包括vCenter Server、ESXi、VMFS5和VMFS6数据存储库
* vSphere 7.0 Update 3、包括使用Spring Framework 4的vCenter Server、ESXi、VMFS5和VMFS6数据存储库
+

IMPORTANT: 升级到VMware vCenter Server 7.0 U3时、Element插件无法部署。要使用Spring Framework 4解决此问题描述 、请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/vCenter_plug-in_deployment_fails_after_upgrading_vCenter_to_version_7.0_U3["此知识库文章"^]。

* vSphere 6.7 和 6.7 Update 1 和 3 ，包括 vCenter Server ， ESXi 以及 VMFS5 和 VMFS6 数据存储库
+

IMPORTANT: 此插件与 HTML5 vSphere Web Client 的 6.7 U2 内部版本 13007421 以及更新 2a （内部版本 13643870 ）之前发布的其他 6.7 U2 内部版本不兼容。它与适用于 Flash/FLEX 的 vSphere Web Client 6.7 U2 版兼容。

* vSphere 6.5、包括vCenter Server、ESXi、VMFS5和VMFS6数据存储库
+

IMPORTANT: 此插件与适用于vCenter 4.6、4.7和4.8的Element插件6.5版不兼容。



.停止 vSphere 6.0 支持

IMPORTANT: VMware vSphere 6.0 已于 2020 年 3 月 12 日停止支持。从 NetApp HCI 1.8 和 Element 12 开始，不再支持 vSphere 6.0 。有关详细信息，请参见此 https://mysupport.netapp.com/info/communications/ECMLP2863840.html["产品公告"]。

--
====


== vSphere 兼容性和最佳实践

在使用此插件之前，请考虑以下功能和建议：

* 不支持 vCenter 高可用性（ VCHA ）。
* 由于数据存储库是使用选定 ESXi 主机支持的最高 VMFS 版本创建的，因此所有集群成员都应运行相同版本的 vSphere 和 ESXi ，以避免出现 VMFS 兼容性问题。
* vSphere HTML5 Web Client 和 Flash Web Client 具有单独的数据库，这些数据库不能组合使用。在一个客户端中添加的集群在另一个客户端中不可见。如果要同时使用这两个客户端，请在这两个客户端中添加集群。




== NetApp Element 支持

此插件支持以下主要版本：

* Element 12.x
* Element 11.x




== 网络端口要求

您需要允许某些 TCP 端口通过数据中心的边缘防火墙，以便可以远程管理系统，并允许数据中心外部的客户端连接到资源。有关 NetApp HCI 和 SolidFire 系统中使用的端口的完整列表，请参见此部分 link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html["页面。"]。



== 了解更多信息

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]

