---
sidebar: sidebar 
permalink: rn_whatsnew_vcp.html 
summary: 了解此版本的适用于VMware vCenter Server的NetApp Element 插件中的新增功能。 
keywords: netapp, vcp, vcenter, plugin, element, new, whats new 
---
= 适用于VMware vCenter Server的NetApp Element 插件中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Element vCenter插件5.4版中没有新的增强功能。

Element vCenter插件5.4随2.26.30版本的管理服务一起提供。 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP3330676["了解更多信息。"^]



== 适用于vCenter Server 5.3的NetApp Element插件

适用于vCenter Server 5.3的NetApp Element插件可提高安全性和性能。 https://library.netapp.com/ecm/ecm_download_file/ECMLP3316480["了解更多信息。"^]。

Element vCenter插件5.3随管理服务2.25.42版提供。



== 适用于vCenter Server 5.2的NetApp Element插件

适用于vCenter Server 5.2的NetApp Element插件对可支持性进行了改进、并对自定义保护域显示进行了增强。

在版本5.2中、如果在Element软件集群上配置了自定义保护域、则此插件将显示自定义保护域运行状况信息。 link:vcp_task_reports_overview.html#reporting-overview-page-data["了解更多信息。"]。

Element vCenter插件5.2随管理服务2.24.40版提供。



== 适用于vCenter Server 5.1的NetApp Element插件

适用于vCenter Server 5.1的NetApp Element 插件可提高安全性和性能。 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885734["了解更多信息。"^]。



== 适用于vCenter Server 5.0的NetApp Element 插件

适用于vCenter Server 5.0的NetApp Element 插件包含远程插件架构、该架构可将插件功能集成到vSphere Client中、而无需在vCenter Server中运行。远程架构支持插件隔离、并支持横向扩展在大型vSphere环境中运行的插件。远程Element插件随管理服务一起部署在管理节点内的Docker容器中。 link:vcp_concept_remote_plugin_architecture.html["了解更多信息。"]。

Element vCenter插件5.0支持VMware vSphere 8.0、7.0和7.0 Update 1、2和3、包括vCenter Server、ESXi和vSphere HTML5 Web Client。

Element vCenter插件5.0可用于2.22.7版的管理服务。如果不使用此插件、则此升级为可选升级、因为所有其他服务和功能均与版本2.21.61相同。有关最新管理服务更新的信息、请参见 https://library.netapp.com/ecm/ecm_download_file/ECMLP2884458["管理服务发行说明2.21.61"^]。



== 适用于vCenter Server 4.10的NetApp Element 插件

Element vCenter插件4.10包含已解决的问题、包括安全漏洞、这些问题可能会显著减少升级期间出现的中断、并增强某些环境中的日常操作。在该插件的4.10版中、联机帮助链接已过渡到此版本 link:index.html["文档链接"]。要从插件中访问联机帮助链接、您必须能够访问网络。

Element vCenter插件4.10可用于2.21.61版的管理服务。



== 适用于vCenter Server 4.9的NetApp Element 插件

适用于vCenter Server 4.9的NetApp Element 插件可恢复对vSphere 6.5的支持、包括vCenter Server、ESXi和vSphere HTML5 Web Client。

Element vCenter插件4.9可用于管理服务2.20.69版。



== 适用于vCenter Server的NetApp Element 插件4.8

Element vCenter插件4.8提供了一些安全改进功能、内存利用率改进功能以及第三方库升级功能。

Element vCenter插件4.8可在2.19版管理服务中使用。



== 适用于 vCenter Server 的 NetApp Element 插件 4.7

Element vCenter插件4.7提供了重要的安全改进功能、进一步改进了中的功能 https://security.netapp.com/advisory/ntap-20210315-0001/["最新的管理服务 2.17.56 修补程序"] 版本。

在 4.7 版中，此插件现在支持 vSphere 7.0 Update 2 的组件，包括 vCenter Server ， ESXi 和 vSphere HTML5 Web Client 。

Element vCenter插件4.7可在2.18版管理服务中使用。



== 适用于 vCenter Server 的 NetApp Element 插件 4.6

在 4.6 版中，此插件现在支持 vSphere 7.0 Update 1 的组件，包括 vCenter Server ， ESXi 和 vSphere HTML5 Web Client 。

管理服务的2.16版提供了Element vCenter插件4.6。



== 了解更多信息

* link:reference_earlier_versions.html["早期版本的 NetApp Element 插件文档"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["混合云控制和管理服务发行说明知识库"^]
* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]

