---
sidebar: sidebar 
permalink: task_vcp_remove.html 
summary: 升级到适用于 vCenter Server 的最新 NetApp Element 插件。 
keywords: netapp, vcp, vcenter, plugin, element, upgrade 
---
= 删除 vCenter 插件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, vcp, vcenter, plugin, element, upgrade


[role="lead"]
对于与 vSphere 6.7 或更早版本结合使用的 vCenter 插件 2.5 或更高版本，您必须完成以下过程才能从 vCenter Server 中手动删除与此插件关联的所有文件。对于 vSphere 7.0 ，注销插件后，所有文件都将自动删除。

.您需要什么？ #8217 ；将需要什么
* vCenter 插件 2.5 或更高版本
* vSphere 6.7 或更早版本
* 您已拥有 link:task_vcp_unregister.html["已取消注册"] 现有插件并与 vCSA 或 vCenter Server 建立 SSH ， RDP 或其他适当连接。


.步骤
. 以管理员身份登录到运行 vCenter Server 的服务器，然后打开命令提示符。
. 停止 vCenter Server 服务：
+
** Windows
+
*** （对于 Flash 客户端）运行以下命令：
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --stop vsphere-client
----
*** （对于 HTML5 客户端）运行以下命令：
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --stop vsphere-client
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --stop vsphere-ui
----


** vCenter Server 设备（ vCSA ）
+
*** （对于 Flash 客户端）运行以下命令：
+
[listing]
----
service-control --stop vsphere-client
----
*** （对于 HTML5 客户端）运行以下命令：
+
[listing]
----
service-control --stop vsphere-client
service-control --stop vsphere-ui
----




. 从以下位置删除 SolidFire 文件夹和文件：
+
** （对于 Windows ）使用 Windows 资源管理器在 `C ： \ProgramData\VMware` 和 `C ： \Program Files\VMware` 中搜索 SolidFire` 。
+

NOTE: 此时将隐藏 ProgramData 文件夹。要访问此文件夹，必须输入完整的文件路径。

** （对于 vCSA ）运行以下命令：
+
[listing]
----
find / -name "*solidfire*" -exec rm -rf {} \;
----


. 启动 vCenter Server 服务：
+
** Windows
+
*** （对于 Flash 客户端）运行以下命令：
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --start vsphere-client
----
*** （对于 HTML5 客户端）运行以下命令：
+
[listing]
----
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --start vsphere-client
C:\Program Files\VMware\vCenter Server\vmon>.\vmon-cli --start vsphere-ui
----


** vCSA ：
+
*** （对于 Flash 客户端）运行以下命令：
+
[listing]
----
service-control --start vsphere-client
----
*** （对于 HTML5 客户端）运行以下命令：
+
[listing]
----
service-control --start vsphere-client
service-control --start vsphere-ui
----






[discrete]
== 了解更多信息

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]

