---
sidebar: sidebar 
permalink: vcp_task_add_manage_nodes.html 
summary: 您可以使用此插件在集群配置中创建和管理节点。 
keywords: netapp, nodes, create, manage, delete, view vcp, vcenter, element 
---
= 添加和管理节点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用此插件、您可以添加 https://docs.netapp.com/us-en/hci/docs/concept_hci_nodes.html#storage-nodes["存储节点"] 创建集群或需要更多存储时。您还可以添加运行Element软件的存储节点。您必须在vSphere中将NetApp HCI 计算节点添加到此插件之外。

*  a node to a cluster
*  node details
*  a node
*  down a node
*  a node from a cluster




== 将节点添加到集群

您可以使用 vCenter 插件将存储节点添加到集群中。

.您需要什么？ #8217 ；将需要什么
* 您要添加的节点已设置，启动和配置。
* 集群中每个节点上的软件的主要或次要版本号必须匹配，软件才能兼容。例如， Element 9.0 与 9.1 版不兼容。



NOTE: 如果要添加的节点的 NetApp Element 软件主要或次要版本与集群上运行的版本不同，则集群会异步将节点更新到集群主节点上运行的 NetApp Element 软件版本。更新节点后，它会自动将自己添加到集群中。在此异步过程中，节点将处于 `pendingActive` 状态。

首次打开电源时，节点需要进行初始配置。设置和配置节点后、它会在配置节点时标识的集群上注册自身、并显示在插件扩展点*集群>节点*页面上的待定节点列表中。

您可以向现有集群添加容量较小或较大的节点。

添加运行NetApp Element 软件的FC节点或存储节点时、操作步骤 是相同的。

.步骤
. 在vSphere Web Client中、打开*集群*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>集群*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>集群*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 单击 * 节点 * 子选项卡。
. 从下拉列表中选择 * 待定 * 以查看节点列表。
. 要添加一个或多个节点，请执行以下步骤：
+
.. 选中要添加的每个节点对应的复选框。
.. 单击 * 添加节点 * 。


. 查看要添加的节点的详细信息并确认此操作。
+
操作完成后，此节点将显示在集群的活动节点列表中。





== 查看节点详细信息

您可以通过插件扩展点的"Cluster"选项卡的"Nodes"页面查看集群中节点的列表。要查看活动节点列表，必须选择 Active View 。您可以通过选择来更改此视图 `Pending`， `PendingActive`，和 `All` 选项。

.步骤
. 在vSphere Web Client中、打开*集群*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>集群*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>集群*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 节点 * 子选项卡。
. 选择 * 活动 * 视图。
. 查看存储集群中节点的详细信息。
+
您可以查看节点 ID ，每个节点的名称和状态，已配置的 IOPS ，节点类型，每个节点中的活动驱动器数量以及每个节点的网络信息等信息。





== 重新启动节点

您可以使用插件扩展点重新启动集群中的一个或多个活动节点。

如果要同时重新启动多个节点，则已停止 I/O 并断开所有 iSCSI 会话。

要重新启动集群，您可以选择所有集群节点并执行重新启动。


IMPORTANT: 此方法将重新启动节点上的所有网络服务，从而导致网络连接暂时断开。


NOTE: 此功能在 SolidFire 企业 SDS 集群中不可用。

.步骤
. 在vSphere Web Client中、打开*集群*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>集群*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>集群*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 节点 * 子选项卡。
+
.. 在 * 活动 * 视图中，选中要重新启动的每个节点对应的复选框。
.. 单击 * 操作 * 。
.. 选择 * 重新启动 * 。


. 确认操作。




== 关闭节点

您可以使用插件扩展点关闭集群中的一个或多个活动节点。要关闭集群，您可以选择所有集群节点并同时关闭。

如果要同时重新启动多个节点，则已停止 I/O 并断开所有 iSCSI 会话。

.关于此任务

NOTE: 此功能在 SolidFire 企业 SDS 集群中不可用。

.步骤
. 在vSphere Web Client中、打开*集群*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>集群*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>集群*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 节点 * 子选项卡。
+
.. 在 * 活动 * 视图中，选中要关闭的每个节点对应的复选框。
.. 单击 * 操作 * 。
.. 选择 * 关闭 * 。


. 确认操作。



NOTE: 如果某个节点在任何类型的关闭条件下关闭时间超过 5.5 分钟，则 NetApp Element 软件会确定该节点不会重新加入集群。双 Helix 数据保护将开始将单个复制块写入另一个节点以复制数据。根据节点关闭的时间长度，在节点恢复联机后，可能需要将其驱动器重新添加回集群。



== 从集群中删除节点

当不再需要节点存储或需要维护时，您可以从集群中删除节点，而不会中断服务。

您已从集群中删除节点中的所有驱动器。在 `RemoveDrives` 进程完成且所有数据均已迁移出节点之前，无法删除节点。

NetApp Element 集群中至少需要两个FC节点才能进行FC连接。如果仅连接了一个FC节点、则系统会在事件日志中触发警报、直到您向集群添加另一个FC节点为止、即使所有FC网络流量仍仅在一个FC节点上运行也是如此。

.步骤
. 在vSphere Web Client中、打开*集群*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>集群*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>集群*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 节点 * 子选项卡。
. 要删除一个或多个节点，请执行以下步骤：
+
.. 在 * 活动 * 视图中，选中要删除的每个节点对应的复选框。
.. 单击 * 操作 * 。
.. 选择 * 删除 * 。


. 确认操作。
+
从集群中删除的任何节点都会显示在待定节点列表中。





== 了解更多信息

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]

