---
sidebar: sidebar 
permalink: vcp_task_reports_overview.html 
summary: 使用适用于VMware vCenter Server的NNetApp Element插件的报告页面查看有关集群组件和性能的信息。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report 
---
= 在概述页面上监控集群的整体运行状况
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以从适用于VMware vCenter Server的NetApp Element 插件的NetApp Element 管理扩展点的报告选项卡的概述页面查看选定集群的集群信息、包括整体容量、效率和性能。

.步骤
. 从 vCenter 插件中，选择 * NetApp Element Management* 。
. 选择 * 报告 * 。
. 监控 " 概述 " 页面上的数据。




== 报告概述页面数据

以下数据将显示在 "Reporting Overview" 页面上：

* * 集群容量 * ：块存储，元数据和已配置空间的剩余容量。将指针移动到进度条上方可查看阈值信息。
* * 集群信息 * ：集群专用信息，例如集群名称，集群上运行的 NetApp Element 软件版本， MVIP 和 SVIP 地址以及集群上的节点数， 4k IOPS ，卷和会话数。
+
** * 集群名称 * ：集群的名称。
** * 存储 IP （ SVIP ） * ：存储虚拟 IP 地址（ SVIP ）。
** * 管理 IP （ MVIP ） * ：管理虚拟 IP 地址（ MVIP ）。
** * SVIP VLAN 标记 * ：主 SVIP 地址的 VLAN 标识符。
** * MVIP VLAN 标记 * ：主 MVIP 地址的 VLAN 标识符。
** * 节点计数 * ：集群中活动节点的数量。
** * 集群 4k IOPS* ：集群可以在一秒内读取 / 写入的 4096 （ 4k ）块的数量。
** * Element OS Version* ：集群运行的 NetApp Element 软件版本。
** * 卷计数 * ：集群上的卷总数，不包括虚拟卷。
** * 虚拟卷计数 * ：集群上的虚拟卷总数。
** * iSCSI 会话 * ：连接到集群的 iSCSI 会话。
** * 光纤通道会话 * ：连接到集群的光纤通道会话。


* * 集群效率 * ：考虑到精简配置，重复数据删除和数据压缩的当前使用的系统总容量。计算得出的集群优势是通过比较传统存储设备上不使用精简配置，重复数据删除和数据压缩时的容量利用率来计算得出的。
* * 保护域 * ：集群的保护域监控摘要。
+

NOTE: 保护域功能与双节点集群不兼容。

+
** * 保护域监控级别 * ：用户选择的保护域故障恢复能力级别。可能值为机箱或节点。绿色表示集群能够达到选定监控级别。红色表示集群不再能够达到选定监控级别，需要采取更正操作。
** * 剩余块容量 * ：表示为保持选定故障恢复能力级别而剩余块容量的百分比。
** * 元数据容量 * ：指示是否有足够的元数据容量来从故障中恢复，同时保持数据可用性不中断。正常（绿色）表示集群具有足够的元数据来保持选定监控级别。Full （红色）表示集群不再能够达到选定监控级别，需要采取更正操作。


* * 已配置 IOPS* ：集群上如何过度配置卷 IOPS 的摘要。配置的 IOPS 计算方法是，将集群上所有卷的最小 IOPS ，最大 IOPS 和突发 IOPS 总数之和除以集群的额定最大 IOPS 。
+

NOTE: 例如，如果集群中有四个卷，每个卷的最小 IOPS 为 500 ，最大 IOPS 为 15 ， 000 ，突发 IOPS 为 15 ， 000 ，则最小 IOPS 总数为 2 ， 000 ，最大 IOPS 总数为 60 ， 000 ，突发 IOPS 总数为 60 ， 000 。如果集群的额定最大 IOPS 为 50 ， 000 ，则计算结果如下： * 最小 IOPS* ： 2000/50000 = 0.04x * 最大 IOPS* ： 60000/50000 = 1.20x * 突发 IOPS* ： 60000/50000 = 1.20x 1.00x 1.00x 是基线，在此基线下，已配置的 IOPS 等于集群的额定 IOPS 。

* * 集群运行状况 * ：集群运行状况的硬件，容量和安全组件。颜色代码表示以下内容：
+
** * 绿色 * ：运行状况良好
** * 黄色 * ：严重
** * 红色 * ：错误


* * 集群输入 / 输出 * ：集群上当前运行的 I/O 。这些值是根据先前的 I/O 测量值与当前 I/O 测量值进行计算的。这些是图中显示的测量值：
+
** * 总计 * ：系统中发生的读写 IOPS 的组合。
** * 读取 * ：发生的读取 IOPS 数。
** * 写入 * ：写入 IOPS 的数量。


* * 集群吞吐量 * ：集群上的读取，写入和总带宽活动：
+
** * 总计 * ：集群中用于读取和写入活动的总 MB/ 秒。
** * 读取 * ：集群的读取活动，以 MB/ 秒为单位。
** * 写入 * ：集群的写入活动，以 MB/ 秒为单位。


* * 性能利用率 * ：正在使用的集群 IOPS 百分比。例如，以 100K IOPS 运行的 250K IOPS 集群将显示消耗率为 40% 。




== 了解更多信息

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]

