---
sidebar: sidebar 
permalink: vcp_reference_reports_alert_errors.html 
summary: 下面列出了系统警报、这些警报是信息、警告或错误、可通过使用适用于VMware vCenter Server的NetApp Element 插件的报告页面指示集群的运行状况。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, alert, cluster, performance 
---
= 系统警报列表
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: media/


[role="lead"]
系统会报告每个警报的错误代码、以帮助您确定系统中哪个组件遇到警报以及生成警报的原因。您可以使用插件扩展点查看错误代码：

* 从Element vCenter插件5.0开始、选择* NetApp远程插件>管理>报告>警报*。
* 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element Management> Reporting > Alerts*。


以下列表概述了不同类型的系统警报。

* * 身份验证服务故障 *
+
一个或多个集群节点上的身份验证服务未按预期运行。

+
请联系 NetApp 支持部门以获得帮助。

* * 可用 VirtualNetworkIPAddressLow*
+
IP 地址块中的虚拟网络地址数量较少。

+
要解决此故障，请向虚拟网络地址块添加更多 IP 地址。

* * 块集群完整 *
+
没有足够的可用块存储空间来支持单节点丢失。有关集群填充度级别的详细信息，请参见 GetClusterFullThreshold API 方法。此集群故障指示以下情况之一：

+
** stage3Low （ Warning ）：已超过用户定义的阈值。调整 "Cluster Full" 设置或添加更多节点。
** stage4Critical （ Error ）：没有足够的空间从单节点故障中恢复。不允许创建卷，快照和克隆。
** stage5CompletelyConsumed （严重） 1 ；不允许写入或新的 iSCSI 连接。将保持当前的 iSCSI 连接。写入将失败，直到向集群添加更多容量为止。


+
要解决此故障，请清除或删除卷，或者向存储集群添加另一个存储节点。

* * 块已降级 *
+
由于发生故障，块数据不再完全复制。

+
|===


| severity | Description 


 a| 
警告
 a| 
只能访问块数据的两个完整副本。



 a| 
error
 a| 
只能访问块数据的一个完整副本。



 a| 
严重
 a| 
无法访问块数据的完整副本。

|===
+
* 注： * 警告状态只能发生在三重 Helix 系统上。

+
要解决此故障，请还原任何脱机节点或块服务，或者联系 NetApp 支持部门以获得帮助。

* * 块服务 TooFull*
+
块服务正在使用过多空间。

+
要解决此故障，请添加更多已配置容量。

* * 块服务运行状况不正常 *
+
检测到块服务运行状况不正常：

+
** 严重性 = 警告：不执行任何操作。此警告期限将在 cTimeUntilBSisKiledMSec=330000 毫秒后过期。
** 严重性 = 错误：系统正在自动停用数据并将其数据重新复制到其他运行状况良好的驱动器。
** 严重性 = 严重：多个节点上的故障块服务大于或等于复制计数（双 Helix 为 2 ）。数据不可用，无法完成箱同步。


+
检查网络连接问题和硬件错误。如果特定硬件组件出现故障，则会出现其他故障。当可访问块服务或已停用此服务时，此故障将得以清除。

* * BmcSelfTestFailed
+
基板管理控制器(BMC)未通过自检。

+
请联系NetApp支持部门以获得帮助。

+
在升级到Element 12.5或更高版本期间、 `BmcSelfTestFailed` 如果节点先前存在故障BMC、或者节点的BMC在升级期间出现故障、则不会为该节点生成故障。升级期间未通过自检的BMC将使用问题描述 A `BmcSelfTestFailed` 整个集群完成升级后出现警告故障。

* * 时钟 SkewExceedsFaultThreshold *
+
集群主节点与提供令牌的节点之间的时间偏差超过建议的阈值。存储集群无法自动更正节点之间的时间偏差。

+
要解决此故障，请使用网络内部的 NTP 服务器，而不是使用安装默认值。如果您使用的是内部 NTP 服务器，请联系 NetApp 支持部门以获得帮助。

* * clusterCannotSync*
+
出现空间不足的情况，脱机块存储驱动器上的数据无法同步到仍处于活动状态的驱动器。

+
要解决此故障，请添加更多存储。

* * clusterFull *
+
存储集群中没有更多可用存储空间。

+
要解决此故障，请添加更多存储。

* * 集群 IOPSAreOverProvisioned *
+
集群 IOPS 配置过度。所有最小 QoS IOPS 的总和大于集群的预期 IOPS 。无法同时为所有卷保持最低 QoS 。

+
要解决此问题描述，请降低卷的最小 QoS IOPS 设置。

* * cpuTherMalEventThreshold *
+
一个或多个CPU上的CPU散热事件数超过配置的阈值。

+
如果在10分钟内未检测到新的CPU散热事件、则此警告将自行解决。

* * 禁用 DriveSecurityFailed
+
集群未配置为启用驱动器安全性（空闲加密），但至少有一个驱动器启用了驱动器安全性，这意味着在这些驱动器上禁用驱动器安全性失败。此故障会记录为 "`Warning` " 严重性。

+
要解决此故障，请查看故障详细信息以了解无法禁用驱动器安全保护的原因。可能的原因包括：

+
** 无法获取加密密钥，请调查此密钥或外部密钥服务器的访问问题。
** 对驱动器执行禁用操作失败，请确定是否可能获取了错误的密钥。


+
如果这两种情况都不是导致故障的原因，则可能需要更换驱动器。

+
您可以尝试恢复未成功禁用安全的驱动器，即使提供的身份验证密钥正确也是如此。要执行此操作，请将驱动器移至 "Available" （可用）以从系统中删除，对驱动器执行安全擦除并将其移回 "Active" （活动）。

* * 已断开 ClusterPair*
+
集群对已断开连接或配置不正确。

+
检查集群之间的网络连接。

* * 断开 RemoteNode*
+
远程节点已断开连接或配置不正确。

+
检查节点之间的网络连接。

* * 断开 SnapMirrorEndpoint*
+
远程 SnapMirror 端点已断开连接或配置不正确。

+
检查集群与远程 SnapMirrorEndpoint 之间的网络连接。

* * 可用驱动器 *
+
集群中有一个或多个驱动器可用。通常，所有集群都应添加所有驱动器，而不应使任何驱动器处于可用状态。如果意外出现此故障，请联系 NetApp 支持部门。

+
要解决此故障，请向存储集群添加任何可用驱动器。

* * 驱动器已启用 *
+
当一个或多个驱动器发生故障时，集群将返回此故障，表示以下情况之一：

+
** 驱动器管理器无法访问此驱动器。
** 分区或块服务失败次数过多，可能是由于驱动器读取或写入失败，无法重新启动。
** 驱动器缺失。
** 无法访问节点的主服务（此节点中的所有驱动器均视为缺失 / 故障）。
** 驱动器已锁定，无法获取驱动器的身份验证密钥。
** 驱动器已锁定，解锁操作失败。


+
要解决此问题描述，请执行以下操作：

+
** 检查节点的网络连接。
** 更换驱动器。
** 确保身份验证密钥可用。


* * 驱动器运行状况故障 *
+
驱动器未通过智能运行状况检查，因此驱动器的功能会降低。此故障具有严重严重性级别：

+
** 插槽中序列号为 < 序列号 > 的驱动器： < 节点插槽 >< 驱动器插槽 > 未通过 SMART 整体运行状况检查。


+
要解决此故障，请更换驱动器。

* * 驱动器 WearFault *
+
驱动器的剩余寿命已降至阈值以下，但它仍在运行。此故障可能存在两个严重性级别：严重和警告：

+
** 序列号为 < 序列号 > 的驱动器插槽： < 节点插槽 >< 驱动器插槽 > 具有严重的损耗级别。
** 驱动器的插槽： <node slot><drive slot> 中的序列号为 <serial number> ，因此预留的损耗较低。


+
要解决此故障，请尽快更换驱动器。

* * 双工 ClusterMasterCandidate*
+
检测到多个存储集群候选主存储。

+
请联系 NetApp 支持部门以获得帮助。

* * 启用 DriveSecurityFailed
+
集群已配置为需要驱动器安全性（空闲加密），但至少一个驱动器无法启用驱动器安全性。此故障会记录为 "`Warning` " 严重性。

+
要解决此故障，请查看故障详细信息以了解无法启用驱动器安全保护的原因。可能的原因包括：

+
** 无法获取加密密钥，请调查此密钥或外部密钥服务器的访问问题。
** 驱动器上的启用操作失败，请确定是否可能获取了错误的密钥。如果这两种情况都不是导致故障的原因，则可能需要更换驱动器。


+
您可以尝试恢复未成功启用安全保护的驱动器，即使提供的身份验证密钥正确也是如此。要执行此操作，请将驱动器移至 "Available" （可用）以从系统中删除，对驱动器执行安全擦除并将其移回 "Active" （活动）。

* * 信号群已降级 *
+
一个或多个集合节点已断开网络连接或电源。

+
要解决此故障，请还原网络连接或电源。

* * 异常 *
+
报告的故障不是例行故障。这些故障不会自动从故障队列中清除。

+
请联系 NetApp 支持部门以获得帮助。

* * 故障空间 TooFull*
+
块服务未响应数据写入请求。这会导致分区服务用尽存储失败写入的空间。

+
要解决此故障，请还原块服务功能，以允许继续正常写入并从分区服务刷新故障空间。

* * 风扇传感器 *
+
风扇传感器出现故障或缺失。

+
要解决此故障，请更换任何出现故障的硬件。

* * 光纤通道访问已降级 *
+
光纤通道节点在一段时间内未通过其存储 IP 对存储集群中的其他节点做出响应。在此状态下，节点将被视为无响应并生成集群故障。

+
检查网络连接。

* * 光纤通道访问不可用 *
+
所有光纤通道节点均无响应。此时将显示节点 ID 。

+
检查网络连接。

* * fibreChannelActiveIxL*
+
IXL Nexus 计数即将达到支持的限制，即每个光纤通道节点具有 8000 个活动会话。

+
** 最佳实践限制为 5500 。
** 警告限制为 7500 。
** 最大限制（未强制实施）为 8192 。


+
要解决此故障，请将 IXL Nexus 计数降至最佳实践限制 5500 以下。

* * fibreChannelConfig*
+
此集群故障指示以下情况之一：

+
** PCI 插槽上存在意外的光纤通道端口。
** 存在意外的光纤通道 HBA 型号。
** 光纤通道 HBA 的固件存在问题。
** 光纤通道端口未联机。
** 有一个永久性问题描述正在配置光纤通道直通。


+
请联系 NetApp 支持部门以获得帮助。

* * 光纤通道 IOPS*
+
集群中光纤通道节点的总 IOPS 计数即将达到 IOPS 限制。限制包括：

+
** FC0025 ：每个光纤通道节点 4 k 块大小时的 IOPS 限制为 450 k 。
** FCN001 ：每个光纤通道节点 4 K 块大小时的 625K 操作数限制。


+
要解决此故障，请在所有可用光纤通道节点之间平衡负载。

* * fibreChannelStaticIxL*
+
IXL Nexus 计数即将达到支持的限制，即每个光纤通道节点有 16000 个静态会话。

+
** 最佳实践限制为 11000 。
** 警告限制为 15000 。
** 最大限制（强制实施）为 16384 。


+
要解决此故障，请将 IXL Nexus 计数降至最佳实践限制 11000 以下。

* * 文件系统容量低 *
+
其中一个文件系统空间不足。

+
要解决此故障，请向文件系统添加更多容量。

* *文件系统IsReadOnly *
+
文件系统已移至只读模式。

+
请联系 NetApp 支持部门以获得帮助。

* * fipsDrivesMismatch*
+
已将非 FIPS 驱动器物理插入支持 FIPS 的存储节点，或者已将 FIPS 驱动器物理插入非 FIPS 存储节点。每个节点会生成一个故障，并列出所有受影响的驱动器。

+
要解决此故障，请卸下或更换不匹配的相关驱动器。

* * fipsDrivesOutOfCompliance"
+
在启用 FIPS 驱动器功能后，系统检测到已禁用空闲加密。如果启用了 FIPS 驱动器功能且存储集群中存在非 FIPS 驱动器或节点，则也会生成此故障。

+
要解决此故障，请启用空闲加密或从存储集群中删除非 FIPS 硬件。

* * fipsSelfTestFailure*
+
FIPS 子系统在自检期间检测到故障。

+
请联系 NetApp 支持部门以获得帮助。

* * 硬件配置不匹配 *
+
此集群故障指示以下情况之一：

+
** 此配置与节点定义不匹配。
** 此类节点的驱动器大小不正确。
** 检测到不受支持的驱动器。可能的原因是，安装的 Element 版本无法识别此驱动器。建议更新此节点上的 Element 软件。
** 驱动器固件不匹配。
** 驱动器加密功能状态与节点不匹配。


+
请联系 NetApp 支持部门以获得帮助。

* * idPCertificateExpiration*
+
用于第三方身份提供程序（ IdP ）的集群服务提供商 SSL 证书即将到期或已过期。此故障会根据紧急程度使用以下严重性：

+
|===


| severity | Description 


 a| 
警告
 a| 
证书将在 30 天内过期。



 a| 
error
 a| 
证书将在 7 天内过期。



 a| 
严重
 a| 
证书将在 3 天内过期或已过期。

|===
+
要解决此故障，请在 SSL 证书过期之前对其进行更新。将UpdateIdpConfiguration API方法与结合使用 `refreshCertificateExpirationTime=true` 以提供更新后的SSL证书。

* * 不一致的绑定模式 *
+
VLAN 设备上缺少绑定模式。此故障将显示预期的绑定模式和当前正在使用的绑定模式。



* * 不一致的 Mtus*
+
此集群故障指示以下情况之一：

+
** Bond1G mismatch ：在绑定 1G 接口上检测到 MTU 不一致。
** Bond10G mismatch ：在绑定 10G 接口上检测到 MTU 不一致。


+
此故障将显示相关节点以及关联的 MTU 值。

* * 不一致的路由规则 *
+
此接口的路由规则不一致。

* * 不一致的子网询问 *
+
VLAN 设备上的网络掩码与内部记录的 VLAN 网络掩码不匹配。此故障将显示预期的网络掩码和当前正在使用的网络掩码。

* * 绑定端口数不正确 *
+
绑定端口数不正确。

* * invuidConfiguredFibreChannelNodeCount*
+
两个预期光纤通道节点连接中的一个已降级。如果仅连接了一个光纤通道节点，则会出现此故障。

+
要解决此故障，请检查集群网络连接和网络布线，并检查服务是否出现故障。如果没有网络或服务问题，请联系 NetApp 支持部门更换光纤通道节点。

* * irqBalanceFailed
+
尝试平衡中断时出现异常。

+
请联系 NetApp 支持部门以获得帮助。

* * kmipCertificateFault ：
+
** 根证书颁发机构（ CA ）证书即将到期。
+
要解决此故障，请从根 CA 获取一个新证书，此证书的到期日期至少为 30 天后，并使用 ModifyKeyServerKmip 提供更新后的根 CA 证书。

** 客户端证书即将到期。
+
要解决此故障，请使用 GetClientCertificateSigningRequest 创建一个新的 CSR ，并对其进行签名以确保新的到期日期至少在 30 天后，然后使用 ModifyKeyServerKmip 将即将到期的 KMIP 客户端证书替换为新证书。

** 根证书颁发机构（ CA ）证书已过期。
+
要解决此故障，请从根 CA 获取一个新证书，此证书的到期日期至少为 30 天后，并使用 ModifyKeyServerKmip 提供更新后的根 CA 证书。

** 客户端证书已过期。
+
要解决此故障，请使用 GetClientCertificateSigningRequest 创建一个新的 CSR ，并对其进行签名以确保新的到期日期至少在 30 天后，然后使用 ModifyKeyServerKmip 将已过期的 KMIP 客户端证书替换为新证书。

** 根证书颁发机构（ CA ）证书错误。
+
要解决此故障，请检查提供的证书是否正确，如果需要，请从根 CA 重新获取此证书。使用 ModifyKeyServerKmip 安装正确的 KMIP 客户端证书。

** 客户端证书错误。
+
要解决此故障，请检查是否安装了正确的 KMIP 客户端证书。客户端证书的根 CA 应安装在 EKS 上。使用 ModifyKeyServerKmip 安装正确的 KMIP 客户端证书。



* * kmipServerFault * ：
+
** 连接失败
+
要解决此故障，请检查外部密钥服务器是否处于活动状态并可通过网络访问。使用 TestKeyServerKimp 和 TestKeyProviderKmip 测试连接。

** 身份验证失败
+
要解决此故障，请检查使用的根 CA 和 KMIP 客户端证书是否正确，以及私钥和 KMIP 客户端证书是否匹配。

** 服务器错误
+
要解决此故障，请查看此错误的详细信息。根据返回的错误，可能需要在外部密钥服务器上进行故障排除。



* * 内存 EccThreshold *
+
检测到大量可更正或不可更正的 ECC 错误。此故障会根据紧急程度使用以下严重性：

+
|===


| 事件 | severity | Description 


 a| 
一个 DIMM cErrorCount 达到 cDImmCorrectableErrWarnThreshold 。
 a| 
警告
 a| 
DIMM 上的可更正 ECC 内存错误超过阈值： <Processor> <DIMM Slot>



 a| 
在 DIMM 的 cErrorFault计时 器过期之前，一个 DIMM cErrorCount 将保持在 cDIMMCorrectableErrWarnThreshold 以上。
 a| 
error
 a| 
DIMM <Processor> <DIMM> 上的可更正 ECC 内存错误超过阈值



 a| 
内存控制器报告 cErrorCount 高于 cMemCtrl+Alt+CorrectErrWarnThreshold ，并指定 cMemcerrCorrectableErrWarnDuration 。
 a| 
警告
 a| 
内存控制器 <Processor> <Memory Controller> 上的可更正 ECC 内存错误超过阈值



 a| 
在内存控制器的 cErrorFault计时 器过期之前，内存控制器会报告 cErrorCount 高于 cMemCtrl+Alt+CorrectErrWarnThreshold 。
 a| 
error
 a| 
DIMM <Processor> <DIMM> 上的可更正 ECC 内存错误超过阈值



 a| 
单个 DIMM 报告的 uErrorCount 超过零，但小于 cdimmUncorrecteErrFaultThreshold 。
 a| 
警告
 a| 
在 DIMM ： <Processor> <DIMM Slot> 上检测到不可更正的 ECC 内存错误



 a| 
单个 DIMM 报告的 uErrorCount 至少为 cDIMMUncorrectErrFaultThreshold 。
 a| 
error
 a| 
在 DIMM ： <Processor> <DIMM Slot> 上检测到不可更正的 ECC 内存错误



 a| 
内存控制器报告 uErrorCount 超过零，但小于 cMemcerrUncorrectErrFaultThreshold 。
 a| 
警告
 a| 
在内存控制器 < 处理器 > < 内存控制器 > 上检测到不可更正的 ECC 内存错误



 a| 
内存控制器报告的 uErrorCount 至少为 cMemcerrcerr无法 更正 ErrFaultThreshold 。
 a| 
error
 a| 
在内存控制器 < 处理器 > < 内存控制器 > 上检测到不可更正的 ECC 内存错误

|===
+
要解决此故障，请联系 NetApp 支持部门以获得帮助。

* * 内存使用阈值 *
+
内存使用量超过正常值。此故障会根据紧急程度使用以下严重性：

+

NOTE: 有关故障类型的更多详细信息，请参见错误故障中的 * 详细信息 * 标题。

+
|===


| severity | Description 


 a| 
警告
 a| 
系统内存不足。



 a| 
error
 a| 
系统内存非常低。



 a| 
严重
 a| 
系统内存已完全耗尽。

|===
+
要解决此故障，请联系 NetApp 支持部门以获得帮助。

* * 元数据 ClusterFull*
+
没有足够的可用元数据存储空间来支持单节点丢失。有关集群填充度级别的详细信息，请参见 GetClusterFullThreshold API 方法。此集群故障指示以下情况之一：

+
** stage3Low （ Warning ）：已超过用户定义的阈值。调整 "Cluster Full" 设置或添加更多节点。
** stage4Critical （ Error ）：没有足够的空间从单节点故障中恢复。不允许创建卷，快照和克隆。
** stage5CompletelyConsumed （严重） 1 ；不允许写入或新的 iSCSI 连接。将保持当前的 iSCSI 连接。写入将失败，直到向集群添加更多容量为止。清除或删除数据或添加更多节点。


+
要解决此故障，请清除或删除卷，或者向存储集群添加另一个存储节点。

* * mtuCheckFailure *
+
未为网络设备配置正确的 MTU 大小。

+
要解决此故障，请确保为所有网络接口和交换机端口配置巨型帧（ MTU 大小高达 9000 字节）。

* * 网络配置 *
+
此集群故障指示以下情况之一：

+
** 预期接口不存在。
** 存在重复接口。
** 已配置的接口已关闭。
** 需要重新启动网络。


+
请联系 NetApp 支持部门以获得帮助。

* * 节点可用虚拟网络 IP 插件 *
+
IP 地址块中没有可用的虚拟网络地址。

+
** virtualNetworkID #标记(###)没有可用的存储IP地址。无法向集群添加其他节点。


+
要解决此故障，请向虚拟网络地址块添加更多 IP 地址。

* *nodeHardwareFault （网络接口 <name> 已关闭或缆线已拔出） *
+
网络接口已关闭或已拔下缆线。

+
要解决此故障，请检查一个或多个节点的网络连接。

* *nodeHardwareFault （驱动器加密功能状态与插槽 <node slot><drive slot> 中驱动器的节点加密功能状态不匹配） *
+
驱动器的加密功能与安装该驱动器的存储节点不匹配。

* * 节点 HardwareFault （此节点类型的插槽 < 驱动器插槽 >< 驱动器插槽 > 中驱动器的驱动器 < 驱动器类型 > 驱动器大小 < 实际大小 > 不正确 - 应为 < 预期大小 > ） *
+
存储节点中的驱动器大小不正确。

* * 节点硬件故障（在插槽 < 节点插槽 >< 驱动器插槽 > 中检测到不支持的驱动器；驱动器统计信息和运行状况信息将不可用） *
+
存储节点包含其不支持的驱动器。

* * 节点硬件故障（插槽 < 节点插槽 >< 驱动器插槽 > 中的驱动器应使用固件版本 < 预期版本 > ，但使用的版本 < 实际版本 > 不受支持） *
+
存储节点包含运行不受支持的固件版本的驱动器。

* * 节点维护模式 *
+
节点已置于维护模式。此故障会根据紧急程度使用以下严重性：

+
|===


| severity | Description 


 a| 
警告
 a| 
指示节点仍处于维护模式。



 a| 
error
 a| 
表示维护模式无法禁用，最可能的原因是备用磁盘出现故障或处于活动状态。

|===
+
要解决此故障，请在维护完成后禁用维护模式。如果错误级别故障仍然存在，请联系 NetApp 支持部门以获得帮助。

* * 节点脱机 *
+
Element 软件无法与指定节点进行通信。检查网络连接。

* * 不使用 LACPBondMode*
+
未配置 LACP 绑定模式。

+
要解决此故障，请在部署存储节点时使用 LACP 绑定；如果未启用并正确配置 LACP ，客户端可能会遇到性能问题。

* * 无法访问 ntpServer*
+
存储集群无法与指定的一个或多个 NTP 服务器进行通信。

+
要解决此故障，请检查 NTP 服务器，网络和防火墙的配置。

* * ntpTimeNotInSync*
+
存储集群时间与指定 NTP 服务器时间之间的差异过大。存储集群无法自动更正此差异。

+
要解决此故障，请使用网络内部的 NTP 服务器，而不是使用安装默认值。如果您使用的是内部 NTP 服务器，并且问题描述仍然存在，请联系 NetApp 支持部门以获得帮助。

* * nvramDeviceStatus*
+
NVRAM 设备出现错误，正在发生故障或已发生故障。此故障具有以下严重性：

+
|===


| severity | Description 


 a| 
警告
 a| 
硬件检测到警告。这种情况可能是暂时的，例如温度警告。

** nvmLifetimeError
** nvmLifetimeStatus
** 生成源 LifetimeStatus
** energySourceTemperatureStatus
** warningThresholdExceeded




 a| 
error
 a| 
硬件检测到错误或严重状态。集群主节点尝试从操作中删除分区驱动器（此操作会生成驱动器删除事件）。如果二级分区服务不可用，则不会删除驱动器。除了警告级别错误之外，还返回错误：

** NVRAM 设备挂载点不存在。
** NVRAM 设备分区不存在。
** NVRAM 设备分区已存在，但未挂载。




 a| 
严重
 a| 
硬件检测到错误或严重状态。集群主节点尝试从操作中删除分区驱动器（此操作会生成驱动器删除事件）。如果二级分区服务不可用，则不会删除驱动器。

** 持久性 Lost
** armStatusSaveNarm
** csaveStatusError


|===
+
更换节点中的所有故障硬件。如果无法解决问题描述问题，请联系 NetApp 支持部门以获得帮助。

* * 电源供应错误 *
+
此集群故障指示以下情况之一：

+
** 电源不存在。
** 电源出现故障。
** 电源输入缺失或超出范围。


+
要解决此故障，请验证是否已为所有节点提供冗余电源。请联系 NetApp 支持部门以获得帮助。

* * 配置空间 TooFull*
+
集群的整体已配置容量过满。

+
要解决此故障，请添加更多已配置空间，或者删除并清除卷。

* * remoteRePAsyncDelayExceedd*
+
已超过为复制配置的异步延迟。检查集群之间的网络连接。

* * 远程 remoteClusterFull*
+
卷已暂停远程复制，因为目标存储集群太满。

+
要解决此故障，请释放目标存储集群上的一些空间。

* * remoteSnapshotClusterFull*
+
由于目标存储集群太满，卷已暂停快照远程复制。

+
要解决此故障，请释放目标存储集群上的一些空间。

* * remoteSnapshotsExceededLimit*
+
由于目标存储集群卷已超过其快照限制，卷已暂停快照远程复制。

+
要解决此故障，请增加目标存储集群上的快照限制。

* * 计划操作错误 *
+
已运行一个或多个计划活动，但失败。

+
如果计划活动再次运行并成功，计划活动已删除或活动已暂停并恢复，则此故障将清除。

* * 传感器读取已成功 *
+
传感器无法与基板管理控制器(BMC)通信。

+
请联系 NetApp 支持部门以获得帮助。

* * 服务未运行 *
+
所需服务未运行。

+
请联系 NetApp 支持部门以获得帮助。

* * sliceServiceTooFull*
+
为分区服务分配的已配置容量太少。

+
要解决此故障，请添加更多已配置容量。

* * sliceServiceUnhealth*
+
系统已检测到分区服务运行状况不正常，并且正在自动停用该服务。

+
** 严重性 = 警告：不执行任何操作。此警告期限将在 6 分钟后过期。
** 严重性 = 错误：系统正在自动停用数据并将其数据重新复制到其他运行状况良好的驱动器。


+
检查网络连接问题和硬件错误。如果特定硬件组件出现故障，则会出现其他故障。当分区服务可访问或服务已停用时，此故障将得以清除。

* * 已启用 ssh*
+
已在存储集群中的一个或多个节点上启用 SSH 服务。

+
要解决此故障，请在相应节点上禁用 SSH 服务，或者联系 NetApp 支持部门以获得帮助。

* * sslCertificateExpiration*
+
与此节点关联的 SSL 证书即将到期或已过期。此故障会根据紧急程度使用以下严重性：

+
|===


| severity | Description 


 a| 
警告
 a| 
证书将在 30 天内过期。



 a| 
error
 a| 
证书将在 7 天内过期。



 a| 
严重
 a| 
证书将在 3 天内过期或已过期。

|===
+
要解决此故障，请续订 SSL 证书。如果需要，请联系 NetApp 支持部门以获得帮助。

* * strandedCapacity"
+
单个节点占用的存储集群容量超过一半。

+
为了保持数据冗余，系统会减少最大节点的容量，以使其部分块容量处于孤立状态（未使用）。

+
要解决此故障，请向现有存储节点添加更多驱动器或向集群添加存储节点。

* * TempSensor *
+
温度传感器报告的温度高于正常温度。此故障可能会与 powerSupplyError 或 FanSensor 故障一起触发。

+
要解决此故障，请检查存储集群附近是否存在气流障碍。如果需要，请联系 NetApp 支持部门以获得帮助。

* * 升级 *
+
升级已进行 24 小时以上。

+
要解决此故障，请恢复升级或联系 NetApp 支持部门以获得帮助。

* * 无响应服务 *
+
服务已变得无响应。

+
请联系 NetApp 支持部门以获得帮助。

* * 虚拟网络配置 *
+
此集群故障指示以下情况之一：

+
** 接口不存在。
** 接口上的命名空间不正确。
** 网络掩码不正确。
** IP 地址不正确。
** 某个接口未启动且未运行。
** 节点上存在多余的接口。


+
请联系 NetApp 支持部门以获得帮助。

* * 卷已降级 *
+
二级卷尚未完成复制和同步。同步完成后，此消息将被清除。

* * 卷脱机 *
+
存储集群中的一个或多个卷已脱机。此外，还将出现 * 卷已降级 * 故障。

+
请联系 NetApp 支持部门以获得帮助。


