---
sidebar: sidebar 
permalink: vcp_task_create_manage_access_groups.html 
summary: 您可以使用此插件创建和管理卷访问组。 
keywords: netapp, storage, access groups, vcp, vcenter, element 
---
= 创建和管理卷访问组
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
答 link:https://docs.netapp.com/us-en/hci/docs/concept_hci_volume_access_groups.html["卷访问组"^] 是一组用户可以使用 iSCSI 启动程序或光纤通道启动程序访问的卷。

您可以通过在一组卷中映射 iSCSI 启动程序 IQN 或光纤通道 WWPN 来创建访问组。添加到访问组的每个 IQN 都可以访问组中的每个卷，而无需 CHAP 身份验证。添加到访问组的每个 WWPN 都允许通过光纤通道网络访问此访问组中的卷。

.选项
* <<Create an access group>>
* <<Edit an access group>>
* <<Add volumes to an access group>>
* <<Remove volumes from an access group>>
* <<Delete an access group>>




== 创建访问组

您可以使用一个或多个启动程序创建卷访问组。将光纤通道（ WWPN ）或 iSCSI （ IQN ）客户端启动程序映射到卷访问组中的卷可以在网络和卷之间实现安全的数据 I/O 。

.步骤
. 选择 * NetApp Element 管理 > 管理 * 。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 访问组 * 子选项卡。
. 选择 * 创建访问组 * 。
. 输入卷访问组的名称。
+

TIP: 使用描述性命名最佳实践。如果您的环境中使用了多个集群或 vCenter Server ，这一点尤其重要。

. 从 * 选择启动程序 * 下拉列表中选择一个未分配的 IQN 或 WWPN ，然后单击 * 添加启动程序 * 。
+

NOTE: 创建卷访问组后，可以添加或删除启动程序。

. 单击 * 确定 * 以创建访问组。




== 编辑访问组

您可以从 NetApp Element 管理扩展点编辑卷访问组名称或添加或删除启动程序。

.步骤
. 选择 * NetApp Element 管理 > 管理 * 。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 访问组 * 子选项卡。
. 选中要编辑的卷访问组对应的复选框。
. 选择 * 操作 * 。
. 在显示的菜单中，选择 * 编辑 * 。
. 根据需要更改以下内容：
+
.. 修改访问组名称。
.. 添加或删除启动程序。
+

NOTE: 如果要删除启动程序，请单击垃圾桶图标将其删除。删除启动程序后，它将无法再访问该卷访问组中的卷。对卷的正常帐户访问不会中断。



. 单击 * 确定 * 。




== 将卷添加到访问组

您可以将卷添加到卷访问组。每个卷都可以属于多个卷访问组；您可以从 " 活动卷 " 视图中查看每个卷所属的组。

.您需要什么？ #8217 ；将需要什么
* 必须至少添加并运行一个集群。
* 至少存在一个访问组。
* 至少存在一个活动卷。


.步骤
. 选择 * NetApp Element 管理 > 管理 * 。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷 * 子选项卡。
. 选中要添加到访问组的每个卷对应的复选框。
. 选择 * 操作 * 。
. 选择 * 添加到访问组 * 。
. 确认详细信息并从列表中选择卷访问组。
. 选择 * 确定 * 。




== 从访问组中删除卷

您可以从访问组中删除卷。

从访问组中删除卷后，该组将无法再访问该卷。


IMPORTANT: 从访问组中删除卷可能会中断主机对卷的访问。

. 选择 * NetApp Element 管理 > 管理 * 。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷 * 子选项卡。
. 选中要从访问组中删除的每个卷对应的复选框。
. 选择 * 操作 * 。
. 选择 * 从访问组中删除 * 。
. 确认详细信息，然后选择不再希望访问每个选定卷的卷访问组。
. 选择 * 确定 * 。




== 删除访问组

您可以使用 NetApp Element 管理扩展点删除卷访问组。在删除卷访问组之前，您无需删除启动程序 ID 或解除卷与该组的关联。删除访问组后，对卷的组访问将中断。

.步骤
. 选择 * NetApp Element 管理 > 管理 * 。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 访问组 * 子选项卡。
. 选中要删除的访问组对应的复选框。
. 选择 * 操作 * 。
. 在显示的菜单中，选择 * 删除 * 。
. 确认操作。


[discrete]
== 了解更多信息

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 和 Element 软件文档"^]

