---
sidebar: sidebar 
permalink: vcp_task_protect_remote_replication.html 
summary: 通过实时复制，可以快速创建卷数据的远程副本。 
keywords: netapp, hci, vcp, vcenter, element, protect, replication, remote, cluster 
---
= 在集群之间执行远程复制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
对于运行 NetApp Element 软件的集群，可以通过实时复制快速创建卷数据的远程副本。您可以将一个存储集群与最多四个其他存储集群配对。

您可以从集群对中的任一集群同步或异步复制卷数据，以实现故障转移和故障恢复。您必须先将两个 NetApp Element 集群配对，然后再将每个集群上的卷配对，才能利用实时远程复制功能。

.您需要什么？ #8217 ；将需要什么
* 确保已向此插件至少添加一个集群。
* 确保配对集群的管理网络和存储网络上的所有节点 IP 地址都相互路由。
* 确保所有配对节点的 MTU 相同，并且在集群之间端到端受支持。
* 确保集群上 NetApp Element 软件版本之间的差异不超过一个主要版本。如果差异较大，则必须升级其中一个集群才能执行数据复制。



NOTE: WAN 加速器设备尚未获得 NetApp 认证，无法在复制数据时使用。如果部署在复制数据的两个集群之间，则这些设备可能会干扰数据压缩和重复数据删除。在生产环境中部署任何 WAN 加速器设备之前，请务必对其影响进行全面的评估。

.步骤
.  clusters
.  volumes
.  volume replication
.  a volume relationship after replication
.  volume relationships




== 对集群配对

要使用实时复制功能，您必须首先将两个集群配对。将两个集群配对并连接后，您可以将一个集群上的活动卷配置为持续复制到另一个集群，从而提供持续数据保护（ CDP ）。

如果对源集群和目标集群都具有集群管理员访问权限，则可以使用目标集群的 MVIP 对这两个集群进行配对。如果集群管理员访问权限仅适用于集群对中的一个集群，则可以在目标集群上使用配对密钥来完成集群配对。

.您需要什么？ #8217 ；将需要什么
* 您需要对要配对的一个或两个集群拥有集群管理员权限。
* 确保集群之间的往返延迟小于 2000 毫秒。
* 确保集群上 NetApp Element 软件版本之间的差异不超过一个主要版本。
* 确保已配对集群上的所有节点 IP 均可相互路由。



NOTE: 集群配对要求管理网络上的节点之间具有完全连接。复制需要在存储集群网络上的各个节点之间建立连接。

您可以将一个 NetApp Element 集群与最多四个其他集群配对以复制卷。您还可以将集群组中的集群彼此配对。

选择以下方法之一：

*  clusters using known credentials
*  clusters with a pairing key




=== 使用已知凭据对集群配对

您可以使用一个集群的 MVIP 与另一个集群建立连接，从而将两个集群配对以实现实时复制。要使用此方法，需要对两个集群都具有集群管理员访问权限。

集群管理员用户名和密码用于在集群配对之前对集群访问进行身份验证。

如果 MVIP 未知或无法访问集群，您可以生成配对密钥并使用该密钥对两个集群配对。有关说明，请参见  clusters with a pairing key。

.步骤
. 在vSphere Web Client中、打开*保护*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>配置>保护*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 配置>保护*。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。



. 选择 * 集群对 * 子选项卡。
. 选择 * 创建集群配对 * 。
. 选择以下选项之一：
+
** *已注册集群*：如果配对的远程集群由同一Element vCenter插件实例控制、请选择此项。
** * Credentialed Cluster*：如果远程集群的已知凭据不在Element vCenter插件配置中、请选择此项。


. 如果选择了 * 已注册集群 * ，请从可用集群列表中选择一个集群，然后单击 * 配对 * 。
. 如果选择了 * Credentialed Cluster* ，请执行以下操作：
+
.. 输入远程集群 MVIP 地址。
.. 输入集群管理员用户名。
.. 输入集群管理员密码。
.. 选择 * 开始配对 * 。


. 完成此任务并看到 "Cluster Pairs" 页面后，验证此集群对是否已连接。
. (可选)在远程集群上、使用Element UI或插件扩展点验证集群对是否已连接：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>保护>集群对*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>保护>集群对*。






=== 使用配对密钥对集群配对

如果您对本地集群拥有集群管理员访问权限，但对远程集群没有此权限，则可以使用配对密钥对这些集群进行配对。配对密钥会在本地集群上生成，然后安全地发送给远程站点的集群管理员，以建立连接并完成集群配对以实现实时复制。

此操作步骤介绍了如何使用 vCenter 在本地站点和远程站点上的两个集群之间进行集群配对。对于不受 vCenter 插件控制的集群，您也可以选择 https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_cluster_using_pairing_key.html["开始或完成集群配对"] 使用 Element Web UI 。

[[open_protection_tab]]
.步骤
. 从包含本地集群的vCenter中、打开*保护*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>保护*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>保护*。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。



. 选择 * 集群对 * 子选项卡。
. 选择 * 创建集群配对 * 。
. 选择 * 无法访问集群 * 。
. 选择 * 生成密钥 * 。
+

NOTE: 此操作将生成用于配对的文本密钥，并在本地集群上创建未配置的集群对。如果您未完成操作步骤，则需要手动删除集群对。

. 将集群配对密钥复制到剪贴板。
. 选择 * 关闭 * 。
. 使配对密钥可供远程集群站点的集群管理员访问。
+

NOTE: 集群配对密钥包含一个版本的 MVIP ，用户名，密码和数据库信息，以允许通过卷连接进行远程复制。此密钥应以安全的方式处理，而不是以允许意外或不安全地访问用户名或密码的方式存储。

+

IMPORTANT: 请勿修改配对密钥中的任何字符。如果修改此密钥，则此密钥将无效。

. 从包含远程集群的vCenter中、 ,打开保护选项卡。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

+

NOTE: 您也可以使用 Element UI 完成配对。

. 选择 * 集群对 * 子选项卡。
. 选择 * 完成集群配对 * 。
+

NOTE: 等待加载旋转器消失，然后再继续下一步。如果在配对过程中发生意外错误，请检查并手动删除本地和远程集群上任何未配置的集群对，然后重新执行配对。

. 将配对密钥从本地集群粘贴到 * 集群配对密钥 * 字段中。
. 选择 * 配对集群 * 。
. 完成此任务并看到 * 集群对 * 页面后，请验证集群对是否已连接。
. 要验证集群对是否已连接、请在远程集群上 ,打开保护选项卡 或者使用Element UI。




=== 验证集群对连接

完成集群配对后，您可能需要验证集群对连接以确保复制成功。

.步骤
. 在本地集群上，选择 * 数据保护 * > * 集群对 * 。
. 验证集群对是否已连接。
. 导航回本地集群和 * 集群对 * 窗口，并验证集群对是否已连接。




== 对卷配对

在集群对中的集群之间建立连接后，您可以将一个集群上的卷与该集群对中另一个集群上的卷配对。

您可以使用以下方法之一对卷进行配对：

*  volumes using known credentials：对两个集群使用已知凭据
*  volumes using a pairing key：如果集群凭据仅在源集群上可用，请使用配对密钥。
*  target volumes and pair them with local volumes：如果您知道这两个集群的凭据，请在远程集群上创建一个复制目标卷以与源集群配对。


建立卷配对关系后，您必须确定哪个卷是复制目标：

*  a replication source and target to paired volumes


.您需要什么？ #8217 ；将需要什么
* 您应已在集群对中的集群之间建立连接。
* 您需要对要配对的一个或两个集群拥有集群管理员权限。




=== 使用已知凭据对卷配对

您可以将本地卷与远程集群上的其他卷配对。如果对要配对卷的两个集群都具有集群管理员访问权限，请使用此方法。此方法使用远程集群上卷的卷 ID 启动连接。

.开始之前
* 您具有远程集群的集群管理员凭据。
* 确保包含卷的集群已配对。
* 除非您要在此过程中创建新卷，否则您知道远程卷 ID 。
* 如果要将本地卷作为源卷，请确保将此卷的访问模式设置为读 / 写。


.步骤
. 从包含本地集群的vCenter中、打开*管理*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>管理*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>管理*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷 * 子选项卡。
. 在 * 活动 * 视图中，选中要配对的卷对应的复选框。
. 选择 * 操作 * 。
. 选择 * 卷配对 * 。
. 选择以下选项之一：
+
** * 卷创建 * ：要在远程集群上创建复制目标卷，请选择此项。此方法只能在由Element vCenter插件控制的远程集群上使用。
** *卷选择*：如果目标卷的远程集群由Element vCenter插件控制、请选择此项。
** *卷ID*：如果目标卷的远程集群具有已知凭据、而这些凭据不在Element vCenter插件配置中、请选择此项。


. 选择复制模式：
+
** * 实时（同步） * ：在源集群和目标集群上提交写入后，将向客户端确认写入。
** * 实时（异步） * ：在源集群上提交写入后，将向客户端确认这些写入。
** * 仅限 Snapshot * ：仅复制在源集群上创建的快照。不会复制源卷中的活动写入。


. 如果选择 * 卷创建 * 作为配对模式选项，请执行以下操作：
+
.. 从下拉列表中选择一个配对集群。
+

NOTE: 此操作将填充集群上的可用帐户，以便在下一步中选择。

.. 在目标集群上为复制目标卷选择一个帐户。
.. 输入复制目标卷名称。
+

NOTE: 在此过程中，无法调整卷大小。



. 如果选择 * 卷选择 * 作为配对模式选项，请执行以下操作：
+
.. 选择一个配对集群。
+

NOTE: 此操作将填充集群上的可用卷，以供下一步选择。

.. （可选）如果要在卷配对中将远程卷设置为目标，请选择 * 将远程卷设置为复制目标 * 选项。如果将本地卷设置为读 / 写，则该本地卷将成为对中的源卷。
+

IMPORTANT: 如果您将现有卷分配为复制目标，则该卷上的数据将被覆盖。作为最佳实践，您应使用新卷作为复制目标。

+

NOTE: 您也可以稍后从 * 卷 * > * 操作 * > * 编辑 * 在配对过程中分配复制源和目标。要完成配对，您必须分配一个源和目标。

.. 从可用卷列表中选择一个卷。


. 如果选择 * 卷 ID* 作为配对模式选项，请执行以下操作：
+
.. 从下拉列表中选择一个配对集群。
.. 如果集群未注册到此插件中，请输入集群管理员用户 ID 和集群管理员密码。
.. 输入卷 ID 。
.. 如果要在卷配对中将远程卷设置为目标，请选择 * 将远程卷设置为复制目标 * 选项。如果将本地卷设置为读 / 写，则该本地卷将成为对中的源卷。
+

IMPORTANT: 如果您将现有卷分配为复制目标，则该卷上的数据将被覆盖。作为最佳实践，您应使用新卷作为复制目标。

+

NOTE: 您也可以稍后从 * 卷 * > * 操作 * > * 编辑 * 在配对过程中分配复制源和目标。要完成配对，您必须分配一个源和目标。



. 选择 * 配对 * 。
+

NOTE: 确认配对后，两个集群将开始连接卷。在配对过程中，您可以在卷对页面的卷状态列中看到进度消息。

+

NOTE: 如果尚未将卷分配为复制目标，则配对配置将不完整。卷对将显示 PausedMisconfigured ，直到分配了卷对的源和目标为止。要完成卷配对，您必须分配一个源和目标。

. 在任一集群上选择 * 保护 * > * 卷对 * 。
. 验证卷配对的状态。




=== 使用配对密钥对卷配对

您可以使用配对密钥将本地卷与远程集群上的其他卷配对。如果只有源集群具有集群管理员访问权限，请使用此方法。此方法将生成一个配对密钥，可在远程集群上使用此密钥完成卷对。

.开始之前
* 确保包含卷的集群已配对。
* * 最佳实践 * ：将源卷设置为读 / 写，将目标卷设置为复制目标。目标卷不应包含任何数据，并且与源卷具有完全相同的特征，例如大小， 512e 设置和 QoS 配置。如果您将现有卷分配为复制目标，则该卷上的数据将被覆盖。目标卷的大小可以大于或等于源卷，但不能小于源卷。


此操作步骤介绍了使用 vCenter 在本地站点和远程站点上对两个卷进行卷配对的过程。对于不受 vCenter 插件控制的卷，您也可以使用 Element Web UI 启动或完成卷配对。

有关从 Element Web UI 开始或完成卷配对的说明，请参见 https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_volumes_using_a_pairing_key.html["NetApp Element 软件文档"^]。


NOTE: 卷配对密钥包含经过加密的卷信息，并且可能包含敏感信息。仅以安全方式共享此密钥。

[[open_management]]
.步骤
. 从包含本地集群的vCenter中、打开*管理*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>管理*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>管理*。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。



. 选择 * 卷 * 子选项卡。
. 在 * 活动 * 视图中，选中要配对的卷对应的复选框。
. 选择 * 操作 * 。
. 选择 * 卷配对 * 。
. 选择 * 无法访问集群 * 。
. 选择复制模式：
+
** * 实时（同步） * ：在源集群和目标集群上提交写入后，将向客户端确认写入。
** * 实时（异步） * ：在源集群上提交写入后，将向客户端确认这些写入。
** * 仅限 Snapshot * ：仅复制在源集群上创建的快照。不会复制源卷中的活动写入。


. 选择 * 生成密钥 * 。
+

NOTE: 此操作将生成一个用于配对的文本密钥，并在本地集群上创建一个未配置的卷对。如果不执行此操作，则需要手动删除卷对。

. 将配对密钥复制到剪贴板。
. 选择 * 关闭 * 。
. 使配对密钥可供远程集群站点的集群管理员访问。
+

NOTE: 应以安全的方式对待卷配对密钥，而不是以允许意外或不安全访问的方式存储。

+

IMPORTANT: 请勿修改配对密钥中的任何字符。如果修改此密钥，则此密钥将无效。

. 从包含远程集群的vCenter中、 ,打开管理选项卡。
+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷 * 子选项卡。
. 在 * 活动 * 视图中，选中要配对的卷对应的复选框。
. 选择 * 操作 * 。
. 选择 * 卷配对 * 。
. 选择 * 完成集群配对 * 。
. 将配对密钥从另一个集群粘贴到 * 配对密钥 * 框中。
. 选择 * 完成配对 * 。
+

NOTE: 确认配对后，两个集群将开始连接卷。在配对过程中，您可以在卷对页面的卷状态列中看到进度消息。如果在配对过程中发生意外错误，请检查并手动删除本地和远程集群上任何未配置的集群对，然后重新执行配对。

+

IMPORTANT: 如果尚未将卷分配为复制目标，则配对配置将不完整。卷对将显示 "PausedMisconfigured" ，直到分配了卷对的源和目标为止。要完成卷配对，您必须分配一个源和目标。

. 在任一集群上选择 * 保护 * > * 卷对 * 。
. 验证卷配对的状态。
+

NOTE: 在远程位置完成配对过程后，使用配对密钥配对的卷将显示出来。





=== 创建目标卷并将其与本地卷配对

您可以将远程集群上的两个或多个本地卷与关联目标卷配对。此过程将在远程集群上为您选择的每个本地源卷创建一个复制目标卷。如果对要配对卷的两个集群都具有集群管理员访问权限，并且远程集群由插件控制，请使用此方法。

此方法使用远程集群上每个卷的卷 ID 启动一个或多个连接。

.开始之前
* 确保您具有远程集群的集群管理员凭据。
* 确保包含卷的集群已使用此插件进行配对。
* 确保远程集群由插件控制。
* 确保每个本地卷的访问模式均设置为读 / 写。


.步骤
. 从包含本地集群的vCenter中、打开*管理*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>管理*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>管理*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷 * 子选项卡。
. 从 * 活动 * 视图中，选择要配对的两个或多个卷。
. 选择 * 操作 * 。
. 选择 * 卷配对 * 。
. 选择 * 复制模式 * ：
+
** * 实时（同步） * ：在源集群和目标集群上提交写入后，将向客户端确认写入。
** * 实时（异步） * ：在源集群上提交写入后，将向客户端确认这些写入。
** * 仅限 Snapshot * ：仅复制在源集群上创建的快照。不会复制源卷中的活动写入。


. 从下拉列表中选择一个配对集群。
. 在目标集群上为复制目标卷选择一个帐户。
. （可选）键入目标集群上新卷名称的前缀或后缀。
+

NOTE: 此时将显示一个具有修改后名称的示例卷名称。

. 选择 * 创建对 * 。
+

NOTE: 确认配对后，两个集群将开始连接卷。在配对过程中，您可以在卷对页面的卷状态列中看到进度消息。此过程完成后，将在远程集群上创建并连接新的目标卷。

. 在任一集群上选择 * 保护 * > * 卷对 * 。
. 验证卷配对的状态。




=== 为配对卷分配复制源和目标

如果在卷配对期间未将卷分配为复制目标，则配置将不完整。您可以使用此操作步骤分配源卷及其复制目标卷。复制源或目标可以是卷对中的任一卷。

如果源卷不可用，您也可以使用此操作步骤将数据从源卷重定向到远程目标卷。

您可以访问包含源卷和目标卷的集群。

此操作步骤介绍了如何使用 vCenter 在本地站点和远程站点上的两个集群之间分配源卷和复制卷。对于不受 vCenter 插件控制的卷，您也可以选择此选项 https://docs.netapp.com/us-en/element-software/storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html["分配源卷或复制卷"] 使用 Element Web UI 。

复制源卷具有读 / 写帐户访问权限。复制目标卷只能由复制源以读 / 写方式访问。

* 最佳实践 * ：目标卷不应包含任何数据，并且与源卷具有完全相同的特征，例如大小， 512e 设置和 QoS 配置。目标卷的大小可以大于或等于源卷，但不能小于源卷。

.步骤
. 从插件扩展点选择包含要用作复制源的配对卷的集群：
+
** 从* NetApp远程插件>管理*中的Element vCenter插件5.0开始。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element Management*。


. 从适用于vCenter Server的Element插件版本的扩展点中、选择*管理*选项卡。
. 选择 * 卷 * 子选项卡。
. 在 * 活动 * 视图中，选中要编辑的卷对应的复选框。
. 选择 * 操作 * 。
. 选择 * 编辑 * 。
. 从访问下拉列表中，选择 * 读 / 写 * 。
+

IMPORTANT: 如果要反转源分配和目标分配，此操作将对卷对执行发生原因操作，以显示 PausedMisconfigured ，直到分配新的复制目标为止。更改访问权限会暂停卷复制并导致数据传输停止。请确保您已在两个站点协调这些更改。

. 选择 * 确定 * 。
. 选择包含要用作复制目标的配对卷的集群：
+
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>管理>管理*。
** 从* NetApp远程插件>管理>管理*中的Element vCenter插件5.0开始。


. 选择 * 卷 * 子选项卡。
. 在 * 活动 * 视图中，选中要编辑的卷对应的复选框。
. 选择 * 操作 * 。
. 选择 * 编辑 * 。
. 在 * 访问 * 下拉列表中，选择 * 复制目标 * 。
+

IMPORTANT: 如果您将现有卷分配为复制目标，则该卷上的数据将被覆盖。作为最佳实践，您应使用新卷作为复制目标。

. 选择 * 确定 * 。




== 验证卷复制

复制卷后，您应确保源卷和目标卷处于活动状态。处于 "Active" 状态时，卷将配对，数据将从源卷发送到目标卷，并且数据处于同步状态。

.步骤
. 从包含本地集群的vCenter中、打开*保护*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>保护*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>保护*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷对 * 子选项卡。
. 验证卷状态是否为 "Active" 。




== 复制后删除卷关系

复制完成后，如果您不再需要卷配对关系，则可以删除此卷关系。

请参见  a volume pair。



== 管理卷关系

您可以通过多种方式管理卷关系，例如暂停复制，反转卷配对，更改复制模式，删除卷对或删除集群对。

*  replication
*  the mode of replication
*  a volume pair
*  a cluster pair




=== 暂停复制

您可以编辑卷对属性以手动暂停复制。

.步骤
. 从包含本地集群的vCenter中、打开*保护*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>保护*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>保护*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷对 * 子选项卡。
. 选中要编辑的卷对对应的复选框。
. 选择 * 操作 * 。
. 选择 * 编辑 * 。
. 手动暂停或启动复制过程。
+

IMPORTANT: 手动暂停或恢复卷复制将对数据传输进行发生原因以停止或恢复。请确保您已在两个站点协调这些更改。

. 选择 * 保存更改 * 。




=== 更改复制模式

您可以编辑卷对属性以更改卷对关系的复制模式。

.步骤
. 从包含本地集群的vCenter中、打开*保护*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>保护*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>保护*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷对 * 子选项卡。
. 选中要编辑的卷对对应的复选框。
. 选择 * 操作 * 。
. 选择 * 编辑 * 。
. 选择新的复制模式：
+

IMPORTANT: 更改复制模式会立即更改此模式。请确保您已在两个站点协调这些更改。

+
** * 实时（同步） * ：在源集群和目标集群上提交写入后，将向客户端确认写入。
** * 实时（异步） * ：在源集群上提交写入后，将向客户端确认这些写入。
** * 仅限 Snapshot * ：仅复制在源集群上创建的快照。不会复制源卷中的活动写入。


. 选择 * 保存更改 * 。




=== 删除卷对

如果要删除两个卷之间的对关联，可以删除卷对。

此操作步骤介绍了如何使用 vCenter 在本地站点和远程站点上删除两个卷之间的卷配对关系。

对于不受 vCenter 插件控制的卷，您也可以选择 link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_volume_relationship_after_replication.html["删除卷对端"] 使用 Element Web UI 。

.步骤
. 从包含本地集群的vCenter中、打开*保护*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>保护*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>保护*。


+

NOTE: 如果添加了两个或更多集群，请确保在导航栏中选择要用于此任务的集群。

. 选择 * 卷对 * 子选项卡。
. 选择要删除的一个或多个卷对。
. 选择 * 操作 * 。
. 选择 * 删除 * 。
. 确认每个卷对的详细信息。
+

NOTE: 对于不受此插件管理的集群，此操作仅会删除本地集群上的卷对端。要完全删除此配对关系，您需要手动从远程集群中删除此卷对的一端。

. （对于由插件管理的集群，可选）选中 * 将复制目标访问更改为 * 复选框，然后为复制目标卷选择新的访问模式。删除卷配对关系后，将应用此新访问模式。
. 选择 * 是 * 。




=== 删除集群对

您可以使用 vCenter 在本地站点和远程站点上删除两个集群之间的集群配对关系。要完全删除集群配对关系，必须同时从本地和远程集群中删除集群对端。

您可以使用 vCenter 插件删除集群对的一端

对于不受 vCenter 插件控制的集群，您也可以选择 link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_cluster_pair.html["删除集群对端"] 使用 Element Web UI 。

.步骤
. 从包含本地集群的vCenter中、打开*保护*选项卡：
+
** 从Element vCenter插件5.0开始、选择* NetApp Element 远程插件>管理>保护*。
** 对于Element vCenter插件4.10及更早版本、请选择* NetApp Element 管理>保护*。


. 选择 * 集群对 * 子选项卡。
. 选中要删除的集群对对应的复选框。
. 选择 * 操作 * 。
. 选择 * 删除 * 。
. 确认操作。
+

NOTE: 此操作仅会删除本地集群上的集群对端。要完全删除此配对关系，您需要手动从远程集群中删除此集群对的一端。

. 从集群配对中的远程集群重复上述步骤。




== 卷配对消息和警告

您可以在插件扩展点的保护选项卡的卷对页面上查看已配对或正在配对的卷的信息。从Element vCenter插件5.0开始、从NetApp Element 远程插件扩展点选择管理选项卡。对于Element vCenter插件4.10及更早版本、请选择NetApp Element 管理扩展点。

系统会在卷状态列中显示配对和进度消息。

*  pairing messages
*  pairing warnings




=== 卷配对消息

您可以在初始配对过程中通过插件扩展点的保护选项卡的卷对页面查看消息。这些消息将显示在卷状态列中，并且可以显示在配对的源端和目标端。

* * PausedDisconnected* ：源复制或同步 RPC 超时。与远程集群的连接已断开。检查与集群的网络连接。
* * 正在重新同步连接 * ：远程复制同步现已处于活动状态。开始同步过程并等待数据。
* * 正在重新同步 RRSync* ：正在为配对集群创建卷元数据的单个 Helix 副本。
* * 正在重新同步 LocalSync* ：正在为配对集群创建卷元数据的双 Helix 副本。
* * 正在重新同步 DataTransfer* ：已恢复数据传输。
* * 活动 * ：卷已配对，正在将数据从源卷发送到目标卷，并且数据处于同步状态。
* * 闲置 * ：未发生复制活动。


* 此过程由目标卷驱动，可能不会显示在源卷上。



=== 卷配对警告

在对卷配对后、您可以从插件扩展点的保护选项卡的卷对页面查看警告消息。这些消息将显示在卷状态列中，并且可以显示在配对的源端和目标端。

除非另有说明，否则这些消息可能会显示在配对的源端和目标端。

* * PausedClusterFull* ：由于目标集群已满，因此无法继续进行源复制和批量数据传输。此消息仅显示在对的源端。
* * PausedExceededMaxSnapshotCount* ：目标卷已具有最大快照数，无法复制其他快照。
* * PausedManual* ：本地卷已手动暂停。必须先取消暂停，然后复制才能恢复。
* * PausedManualRemote* ：远程卷处于手动暂停模式。在复制恢复之前，需要手动干预以取消暂停远程卷。
* * PausedMisconfigure* ：正在等待活动源和目标。恢复复制需要手动干预。
* * PausedQoS* ：目标 QoS 无法维持传入 IO 。复制将自动恢复。此消息仅显示在对的源端。
* * PausedSlowLink* ：检测到链路速度较慢并停止复制。复制将自动恢复。此消息仅显示在对的源端。
* * PausedVolumeSizeMismatch* ：目标卷小于源卷。
* * PausedXCopy* ：正在对源卷发出 SCSI XCOPY 命令。必须先完成命令，然后才能恢复复制。此消息仅显示在对的源端。
* * StoppedMisconfigure* ：检测到永久配置错误。远程卷已清除或取消配对。无法执行更正操作；必须建立新的配对。


[discrete]
== 了解更多信息

* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 文档"^]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]

